"""Phase 24 — entity dimension for the Wake Robin study.

Deterministic entity fixtures: perimeter, account scope, balance-sheet
segmentation, and PE commitment exposure — plus the core allocation lenses
(balance-sheet, allocation-vs-target, liquidity). See
``docs/phase_24_entity_study_design_lock.md``.
"""

from aa_model.entity.bridge import holdings_from_positions
from aa_model.entity.crosswalk import (
    liquidity_tier_for,
    policy_class_for,
    policy_class_from_label,
    tier_from_label,
)
from aa_model.entity.curated import (
    CuratedPosition,
    fixture_from_curated_positions,
    read_investment_summary_positions,
)
from aa_model.entity.fixture import (
    PEExposureTotals,
    SegmentTotals,
    canonical_dict,
    canonical_json,
    content_hash,
    load_entity_fixture,
    load_entity_policy,
    load_entity_purpose_policy,
    pe_exposure_totals,
    segment_totals,
)
from aa_model.entity.lenses import (
    AllocationVsTarget,
    AllocationVsTargetRow,
    BalanceSheetLens,
    BurnRate,
    CashFlow,
    CustodianReconResult,
    HoldingsClassGroup,
    HoldingsDetail,
    LiquidityLens,
    LiquidityProjectionLens,
    PurposeAllocation,
    PurposeAllocationRow,
    allocation_vs_target_lens,
    balance_sheet_lens,
    burn_rate_lens,
    cash_flow_lens,
    custodian_reconciliation_lens,
    holdings_detail_lens,
    liquidity_lens,
    liquidity_projection_lens,
    purpose_allocation_lens,
    resolve_holding_purpose,
)
from aa_model.entity.render import export_study_xlsx, render_study_markdown
from aa_model.entity.schemas import (
    BalanceSheetSegmentRecord,
    BurnCategoryRecord,
    CashFlowAssumptions,
    CustodianReconciliation,
    EntityFixture,
    EntityPolicyConfig,
    EntityPurposePolicyConfig,
    HoldingRecord,
    PECommitmentExposureRecord,
    PurposeTargetBand,
    QuarterProjectionRecord,
)

__all__ = [
    "AllocationVsTarget",
    "AllocationVsTargetRow",
    "BalanceSheetLens",
    "BalanceSheetSegmentRecord",
    "BurnCategoryRecord",
    "BurnRate",
    "CashFlow",
    "CashFlowAssumptions",
    "CuratedPosition",
    "CustodianReconResult",
    "CustodianReconciliation",
    "EntityFixture",
    "EntityPolicyConfig",
    "EntityPurposePolicyConfig",
    "PurposeTargetBand",
    "HoldingRecord",
    "HoldingsClassGroup",
    "HoldingsDetail",
    "LiquidityLens",
    "LiquidityProjectionLens",
    "PECommitmentExposureRecord",
    "PEExposureTotals",
    "QuarterProjectionRecord",
    "SegmentTotals",
    "PurposeAllocation",
    "PurposeAllocationRow",
    "allocation_vs_target_lens",
    "balance_sheet_lens",
    "burn_rate_lens",
    "cash_flow_lens",
    "custodian_reconciliation_lens",
    "export_study_xlsx",
    "fixture_from_curated_positions",
    "read_investment_summary_positions",
    "render_study_markdown",
    "tier_from_label",
    "canonical_dict",
    "canonical_json",
    "content_hash",
    "holdings_detail_lens",
    "holdings_from_positions",
    "liquidity_tier_for",
    "policy_class_for",
    "policy_class_from_label",
    "liquidity_lens",
    "purpose_allocation_lens",
    "resolve_holding_purpose",
    "liquidity_projection_lens",
    "load_entity_fixture",
    "load_entity_policy",
    "load_entity_purpose_policy",
    "pe_exposure_totals",
    "segment_totals",
]
