"""Build a CMA candidate from a captured J.P. Morgan LTCMA matrix.

Review-gated candidate generator. Reads the (gitignored) JPM source capture
``data/external/jpm_ltcma_<year>.yaml`` and emits a
:class:`CMAConfig`-shaped candidate at ``configs/cma_jpm.yaml`` for REVIEW.
It never overwrites ``configs/cma.yaml`` and is not loaded by the model.

The emitted candidate uses JPM **arithmetic** returns as the active
``expected_returns_annual`` (correct mean-variance input); JPM **compound**
returns are retained as an annotated companion in the file header. It emits the
6-bucket profile shape: ``cash_and_cash_alts`` is renamed to ``cash`` (the
orchestrator hardcodes a ``cash`` bucket) and ``re_opco_stabilized`` is
excluded ($0, no JPM analog, and a perfect ``real_estate`` duplicate would make
the optimizer covariance singular).

This candidate backs the JPM study profile (``configs/base_jpm.yaml``); it is
not a drop-in for the default ``configs/cma.yaml`` (different taxonomy).

Usage:
    python scripts/build_cma_from_jpm.py
    python scripts/build_cma_from_jpm.py --basis compound
    python scripts/build_cma_from_jpm.py --source data/external/jpm_ltcma_2026.yaml --write
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_SRC = Path(__file__).resolve().parents[1] / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from aa_model.assumptions.jpm_ltcma import (  # noqa: E402
    build_cma_dict,
    compound_returns,
    load_jpm_source,
)
from aa_model.io.schemas import CMAConfig  # noqa: E402

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_SOURCE = _REPO_ROOT / "data" / "external" / "jpm_ltcma_2026.yaml"
_DEFAULT_OUT = _REPO_ROOT / "configs" / "cma_jpm.yaml"

# Profile shape (operator decisions, 2026-07-17):
#  - re_opco_stabilized excluded: no JPM analog, $0 in the book, and (as a
#    perfect real_estate duplicate) it would make the optimizer's covariance
#    singular. It was only ever an alias, so excluding it = not adding it.
#  - cash_and_cash_alts renamed to `cash`: the orchestrator hardcodes a `cash`
#    bucket for inflows / PE calls / spending / costs, so a runnable profile
#    must name its cash bucket `cash`.
_ALIASES: dict[str, str] = {}
_RENAMES = {"cash_and_cash_alts": "cash"}

# JPM does not publish liquidity; sensible defaults keyed by OUTPUT bucket name.
_LIQUIDITY = {
    "equity": "liquid",
    "fixed_income": "liquid",
    "real_estate": "illiquid",
    "pe_buyout": "illiquid",
    "absolute_return": "semi_liquid",
    "cash": "liquid",
}


def _header(source, basis: str, compound: dict[str, float]) -> str:
    lines = [
        "# CMA CANDIDATE derived from J.P. Morgan LTCMA — FOR REVIEW ONLY.",
        "# Generated by scripts/build_cma_from_jpm.py. NOT loaded by the model and",
        "# NOT a drop-in for configs/cma.yaml until allocation.stub_weights is",
        "# expanded to this bucket set (a separate, governed behavior change).",
        "#",
        f"# Source:   {source.provider} LTCMA {source.edition} ({source.currency}),"
        f" data as of {source.as_of}",
        f"# Basis:    expected_returns_annual = {basis.upper()} returns"
        " (mean-variance-correct input)",
        "# Profile:  6 buckets; cash_and_cash_alts->cash (orchestrator hardcodes" " 'cash');",
        "#           re_opco_stabilized excluded ($0, no JPM analog, singular cov).",
        "# Companion compound (geometric) returns, for planning/reporting:",
    ]
    lines += [f"#   {b:20s} {v * 100:6.2f}%" for b, v in compound.items()]
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", default=str(_DEFAULT_SOURCE), help="JPM source capture YAML.")
    ap.add_argument(
        "--basis",
        choices=["arithmetic", "compound"],
        default="arithmetic",
        help="Return basis for the active series (default: arithmetic).",
    )
    ap.add_argument("--out", default=str(_DEFAULT_OUT), help="Candidate output path.")
    ap.add_argument("--write", action="store_true", help="Write the candidate file.")
    args = ap.parse_args()

    source = load_jpm_source(args.source)
    cma = build_cma_dict(
        source,
        return_basis=args.basis,
        aliases=_ALIASES,
        renames=_RENAMES,
        liquidity=_LIQUIDITY,
    )

    # Validate the candidate against the real schema (self-consistency check).
    CMAConfig.model_validate(cma)

    print(
        f"JPM CMA candidate ({args.basis})  |  {source.provider} {source.edition} {source.currency}"
    )
    print(f"{'bucket':20}{'E[R]':>8}{'vol':>8}{'liquidity':>14}")
    for b in cma["expected_returns_annual"]:
        print(
            f"{b:20}{cma['expected_returns_annual'][b]:>8.4f}"
            f"{cma['vol_annual'][b]:>8.4f}{cma['liquidity'][b]:>14}"
        )

    if args.write:
        out = Path(args.out)
        text = _header(
            source,
            args.basis,
            compound_returns(source, aliases=_ALIASES, renames=_RENAMES),
        )
        text += yaml.safe_dump(cma, sort_keys=False)
        out.write_text(text, encoding="utf-8")
        print(f"\nWrote candidate (for review, NOT loaded by the model): {out}")
    else:
        print(f"\n(dry run — pass --write to emit {args.out} for review)")


if __name__ == "__main__":
    main()
